### ISSUE TITLE
ClockFace and circle is placed in wrong position

### ISSUE THREAD

**Issue by stormit-vn** [bartgryszko/react-native-circular-slider#34]
I have replaced and fixed all issues such as PropTypes and remove react-native-svg by using expo. However, the clock face and circle is placed in wrong position.

Can anyone help?

![image](https://user-images.githubusercontent.com/13762258/45289551-a9a77780-b517-11e8-955c-edb39bfff43b.png)

**Comment by HighSoftWare96** [comment]
Compare with #22, the solution is there!

**Comment by stormit-vn** [comment]
@HighSoftWare96  yeah, I also fixed this issue.
