### ISSUE TITLE
Ticks do not line up correctly with numbers

### ISSUE THREAD

**Issue by afshawnlotfi** [bartgryszko/react-native-circular-slider#39]
Hi all the functionality works for the slider however the ticks do not line up with the numbers as seen here. Was wondering why in the demo photo they were but here they are not.
Thanks Afshawn

![Simulator Screen Shot - iPhone Xʀ - 2019-07-19 at 12 45 31](https://user-images.githubusercontent.com/6283745/61551546-7a10a800-aa23-11e9-90d8-fd6b41a9b737.png)

**Comment by sa2812** [comment]
I had the same problem! I fixed it by modifying the package files.

In `node_modules/react-native-circular-slider/ClockFace.js`, edit the following line (line 39 for me)

```
...
 <G transform={{translate: "0, -9"}}>
...
```

I changed it to ` <G transform={{translate: "0, 6"}}>` and that did the trick for me. The exact translation will probably depend on the `fontSize` you use.
